USE [master]
GO
/****** Object:  Database [Contratos_SysCom]    Script Date: 11/03/2025 8:37:54 a.m. ******/
CREATE DATABASE [Contratos_SysCom]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contratos_SysCom', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Contratos_SysCom.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Contratos_SysCom_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Contratos_SysCom_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Contratos_SysCom] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Contratos_SysCom].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Contratos_SysCom] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET ARITHABORT OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Contratos_SysCom] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Contratos_SysCom] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Contratos_SysCom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Contratos_SysCom] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET RECOVERY FULL 
GO
ALTER DATABASE [Contratos_SysCom] SET  MULTI_USER 
GO
ALTER DATABASE [Contratos_SysCom] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Contratos_SysCom] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Contratos_SysCom] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Contratos_SysCom] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Contratos_SysCom] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Contratos_SysCom] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Contratos_SysCom', N'ON'
GO
ALTER DATABASE [Contratos_SysCom] SET QUERY_STORE = ON
GO
ALTER DATABASE [Contratos_SysCom] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Contratos_SysCom]
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 11/03/2025 8:37:55 a.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre_Cargo] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 11/03/2025 8:37:55 a.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[Correo_electronico] [varchar](150) NOT NULL,
	[id_rol] [int] NULL,
	[Fecha_ingreso] [date] NOT NULL,
	[Firma] [text] NULL,
	[Contrato] [varchar](255) NULL,
	[Fecha_eliminacion] [date] NULL,
	[estado] [varchar](10) NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Correo_electronico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT ('Activo') FOR [estado]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [updated_at]
GO
ALTER TABLE [dbo].[Usuarios]  WITH CHECK ADD FOREIGN KEY([id_rol])
REFERENCES [dbo].[Roles] ([id])
ON DELETE SET NULL
GO
USE [master]
GO
ALTER DATABASE [Contratos_SysCom] SET  READ_WRITE 
GO
